INSERT INTO COURSE(
    NAME
)VALUES('YLE');
INSERT INTO COURSE(
    NAME
)VALUES('KET');
INSERT INTO COURSE(
    NAME
)VALUES('PET');
INSERT INTO COURSE(
    NAME
)VALUES('FCE');
INSERT INTO COURSE(
    NAME
)VALUES('IELTS');
INSERT INTO COURSE(
    NAME
)VALUES('DUOLINGO');
INSERT INTO COURSE(
    NAME
)VALUES('TOEIC');
INSERT INTO COURSE(
    NAME
)VALUES('TOEFl');
INSERT INTO COURSE(
    NAME
)VALUES('SAT');
INSERT INTO COURSE(
    NAME
)VALUES('PRE-IGCSE');
INSERT INTO COURSE(
    NAME
)VALUES('IGCSE O LEVEL');
INSERT INTO COURSE(
    NAME
)VALUES('IGCSE A LEVEL');
INSERT INTO COURSE(
    NAME
)VALUES('GED');

INSERT INTO SUBJECT(
    NAME
)VALUES('ENGLISH');
INSERT INTO SUBJECT(
    NAME
)VALUES('MATHEMATICS');
INSERT INTO SUBJECT(
    NAME
)VALUES('ADDITION MATHEMATICS');
INSERT INTO SUBJECT(
    NAME
)VALUES('CHEMISTRY');
INSERT INTO SUBJECT(
    NAME
)VALUES('PHYSICS');
INSERT INTO SUBJECT(
    NAME
)VALUES('BIOLOGY');
INSERT INTO SUBJECT(
    NAME
)VALUES('SOCIAL');
INSERT INTO SUBJECT(
    NAME
)VALUES('COMPUTER SCIENCE');
INSERT INTO SUBJECT(
    NAME
)VALUES('ECONOMICS');
INSERT INTO SUBJECT(
    NAME
)VALUES('BUISNESS');
INSERT INTO SUBJECT(
    NAME
)VALUES('HISTORY');
INSERT INTO SUBJECT(
    NAME
)VALUES('GEOMETRY');
INSERT INTO SUBJECT(
    NAME
)VALUES('COMPASSION');